sudo: required
language: node_js
node_js:
  - '10'
cache:
  directories:
    - ~/.npm
    - node_modules
install:
  - npm install
jobs:
  include:
    - stage: build
      script: 'ng build'
    - stage: prod
      script: 'ng build --prod'
    - stage: test
      dist: xenial
      services:
        - xvfb
      addons:
        chrome: stable
      script:
        - 'ng test --browsers ChromeHeadless --watch=false'
        - 'ng e2e'
stages:
  - build
  - prod
  - test
